spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/urlproject?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
       minimumIdle: 2
       maximumPoolSize: 10
       idleTimeout: 120000
       connectionTimeout: 300000
       leakDetectionThreshold: 300000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      