version: '3.9'  # optional since v1.27.0
services:
  angular-service:
    container_name: angular-container1
    build: ./
    volumes:
      - '.:/app'
    ports:
      - "4201:4200"
    command: >
       bash -c "npm start"
     